### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by alpha970** [KevonneM/Squaak#112]
Hi,
how are you doing?
how config.json look like? I have some issues with configuration

**Comment by KevonneM** [comment]
I used a config for my environmental variables to make deployment easier for me in a linux environment. Create a config file in the directory noted in settings.py. The variables you will need are as follows, a 'SECRET_KEY' variable for the django app, a sendgrid variable named 'SENDGRID_API_KEY' for password resets, an variable named 'appId' and 'appCertificate' from agora.io for videochat functionally.
Alternatively you could use a .env file and store variables there, just don't forget to change how you access the variables in project_structure/settings.py and videochat/views.py.

Contact me for any more help or info, I am glad to help!

**Comment by alpha970** [comment]
Hi,
That's okay.
Thank you for your responses.


Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alpha970** [comment]
hi,
I can run the app now.

But can't create room. When I try to create one, I get this **_VideoChat ID: #adc5d0ef-213c-4eaa-8b4b-3897beeef99d**_

**Comment by KevonneM** [comment]
On the blank screen with the video chat ID open up the browser inpect console, what error message are you receiving?

**Comment by KevonneM** [comment]
It seems the app is unable to find the static files. In settings.py I denoted my static root to be 'staticfiles' to serve them in production. Have you run the collectstatic command? Let me know the outcome!

**Comment by alpha970** [comment]
Hi,
Thank you for your help. Everything is fine now.

**Comment by KevonneM** [comment]
Yes of course!

**Comment by alpha970** [comment]
I am back again!

The chat room doesn't work. when I send a message, I'm not able to see it;

Error in console: 
 Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at chatMessageSend.onclick (http://127.0.0.1:8000/static/js/publicchat.js:48:16)

**Comment by KevonneM** [comment]
Was the web protocol able to upgrade to websockets in the dev tools?

**Comment by alpha970** [comment]
I'am not sure if web protocol able to upgrade to websockets in the dev tools. But I don't know how to set up.
