### ISSUE TITLE
I can not run it 

### ISSUE THREAD

**Issue by Ibrahim-Alamah** [KevonneM/Squaak#114]
I cannot find the etc/config.json .It is missing and connot operate without it.

**Comment by KevonneM** [comment]
> I cannot find the etc/config.json .It is missing and connot operate without it.

That's for environmental variables, you create it yourself to hold those variables. You may also create a .env file to store those variable. I don't provide the secret key or agora ID or certificate.

**Comment by Ibrahim-Alamah** [comment]
how would i create it and what should be written in it
